[package]
name = "model-mem"
version = "0.1.0"
edition = "2021"

[dependencies]
km-checker = { path = "../framework/km-checker" }
km-command = { path = "../framework/km-command" }
rand = "0.8.5"
bitflags = "2.6.0"
postcard = { version = "1.0.8", features = ["alloc"] }